---
title: '**Inference for One Mean**'
subtitle: "Mini-Assignment - MTH 361 A/B - Spring 2023"
header-includes: |
  \usepackage{fancyhdr}
  \pagestyle{fancy}
  \fancyhead[RO,R]{MTH 361 A/B}
  \fancyfoot[CO,C]{}
  \fancyfoot[R]{\thepage}
  \usepackage{float}
  \usepackage{multirow}
output:
  bookdown::pdf_document2:
    toc: no
    number_section: no
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\

**Instructions:**
 
 * Please provide complete solutions for each problem. If it involves mathematical computations, explanations, or analysis, please provide your reasoning or detailed solutions.
 
 * Note that some problems have multiple solutions or ways to solve it. Make sure that your solutions are clear enough to showcase your work and understanding of the material.
 
 * Creativity and collaborations are encouraged. Use all of the resources you have and what you need to complete the mini-assignment. Each student must take personal responsibility and submit their work individually. Please abide by the University of Portland Academic Honor Principle.
 
 * **Please save your work as one pdf file, don't put your name in any part of the document, and submit it to the Teams Assignments for this course. Your document upload will correspond to your name automatically in Teams.**
 
 * If you have questions or concerns, please feel free to ask the instructor.

\newpage

## I. One Mean Inference using the t-Test

### Materials

The exercises below are derived from the textbook [OpenIntro Statistics (4th edition)](https://www.openintro.org/book/os/){target="_blank"} by David Diez, Mine Cetinkaya-Rundel, and Christopher Barr.

### Exercises

1. **Sleep habits of New Yorkers.** New York is known as ``the city that never sleeps". A random sample of 25 New Yorkers were asked how much sleep they get per night. Statistical summaries of these data are shown below. The point estimate suggests New Yorkers sleep less than 8 hours a night on average. Is the result statistically significant?

    ```{=latex}
    \begin{center}
    \begin{tabular}{rrrrrr}
     \hline
    n   & $\bar{x}$ & s     & min   & max \\ 
     \hline
    25  & 7.73      & 0.77  & 6.17  & 9.78 \\ 
      \hline
    \end{tabular}
    \end{center}
    ```

    a. Write the hypotheses in symbols and in words.
    b. Check conditions, then calculate the test statistic, $T$, and the associated degrees of freedom.
    c. Find and interpret the p-value in this context. Drawing a picture may be helpful.
    d. What is the conclusion of the hypothesis test?
    e. If you were to construct a 90\% confidence interval that corresponded to this hypothesis test, would you expect 8 hours to be in the interval?

2. **Play the piano.** Georgianna claims that in a small city renowned for its music school, the average child takes less than 5 years of  piano lessons. We have a random sample of 20 children from the city, with a mean of 4.6 years of piano lessons and a standard deviation of 2.2 years.

    a. Evaluate Georgianna's claim (or that the opposite might be true) using a hypothesis test.
    b. Construct a 95\% confidence interval for the number of years students in this city take piano lessons, and interpret it in context of the data.
    c. Do your results from the hypothesis test and the confidence interval agree? Explain your reasoning.

3. (Outstanding Question) **Working backwards.** 

    a. A 95\% confidence interval for a population mean, $\mu$, is given as (18.985, 21.015). This confidence interval is based on a simple random sample of 36 observations. Calculate the sample mean and standard deviation. Assume that all conditions necessary for inference are satisfied. Use the $t$-distribution in any calculations.
    b. A 90\% confidence interval for a population mean is (65, 77). The population distribution is approximately normal and the population standard deviation is unknown. This confidence interval is based on a simple random sample of 25 observations. Calculate the sample mean, the margin of error, and the sample standard deviation.
