---
title: '**Tentative Topics Schedule**'
subtitle: "Spring 2023 - University of Portland"
---

<br>

<center>**- See Books & Online Resources List for the reading materials -**</center>

<center>[**The readings are not mandatory but it is encouraged.**]{style="color:red"}</center>

<center>[**R Notes and Mini-Assignments will be available during class.**]{style="color:red"}</center>

<center>[**Labs will be available 2-3 weeks before the deadline.**]{style="color:red"}</center>

<br>

The "[\*]" column in the table below contains a number on which it refers to a numbered item in the Books & Online Resources List. For example "[OIS]" refers to the first item in the list, which is our main text book titled "OpenIntro: Statistics 4th Edition".

<br>

## **Topics and Reading Materials**

<br>

| **Week** | **Day** |                             **Topic**                             |   **[OIS]**   |                                      Notes                                       |                                                 **Mini-Assignment**                                                  |                                     **Lab**                                      | **Project** |
|:-------:|:-------:|:-------:|:-------:|:-------:|:----------:|:-------:|:-------:|
|  **1**   | M 1/16  |                            *No Class*                             |      \-       |                                        \-                                        |                                                          \-                                                          |                                        \-                                        |     \-      |
|          | W 1/18  |                    Orientation & Introduction                     |      \-       |      [[slides](notes/1-orientation-and-introduction.html){target="_blank"}]      |                                                          \-                                                          |                                        \-                                        |     \-      |
|          | F 1/20  |                       R Studio & R Markdown                       |      \-       |                                        \-                                        |             [rstudio-and-rmarkdown](https://posit.cloud/spaces/326046/content/5260284){target="_blank"}              |                                        \-                                        |     \-      |
|  **2**   | M 1/23  |                 Data Basics & Sampling Principles                 |   1.2 & 1.3   |  [[slides](notes/2-data-basics-and-sampling-principles.html){target="_blank"}]   |      [data-basics-and-sampling-principles](https://posit.cloud/spaces/326046/content/5272048){target="_blank"}       |              [Lab 1](labs/lab1/intro_to_data.html){target="_blank"}              |     \-      |
|          | W 1/25  |                            Experiments                            |      1.4      |                                        \-                                        |                  [experiments](https://posit.cloud/spaces/326046/content/5283000){target="_blank"}                   |                                        \-                                        |     \-      |
|          | F 1/27  |                            *Cancelled*                            |      \-       |                                        \-                                        |                                                          \-                                                          |                                        \-                                        |     \-      |
|  **3**   | M 1/30  |                     Examining Numerical Data                      |      2.1      |                                        \-                                        |            [examining-numerical-data](https://posit.cloud/spaces/326046/content/5320677){target="_blank"}            |                                        \-                                        |     \-      |
|          |  W 2/1  |                   Considering Categorical Data                    |      2.2      |                                        \-                                        |          [considering-categorical-data](https://posit.cloud/spaces/326046/content/5338446){target="_blank"}          |                                        \-                                        |     \-      |
|          |  F 2/3  |               Case Study: Strokes & Malaria Studies               |   1.1 & 2.3   | [[slides](notes/3-case-study-strokes-and-malaria-studies.html){target="_blank"}] |            [independence-assumption](https://posit.cloud/spaces/326046/content/5350255){target="_blank"}             |                                    Lab 1 Due                                     | Phase 1 Due |
|  **4**   |  M 2/6  |                     Basic Probability Theory                      |      3.1      |                                        \-                                        |            [basic-probability-theory](https://posit.cloud/spaces/326046/content/5367853){target="_blank"}            |                                        \-                                        |     \-      |
|          |  W 2/8  |                      Conditional Probability                      |      3.2      |                                        \-                                        |            [conditional-probability](https://posit.cloud/spaces/326046/content/5383475){target="_blank"}             |                                        \-                                        |     \-      |
|          | F 2/10  |                          Bayes' Theorem                           |      \-       |                                        \-                                        |                 [bayes-theorem](https://posit.cloud/spaces/326046/content/5394475){target="_blank"}                  | [Lab 2](labs/lab2/probability-and-the-normal-distribution.html){target="_blank"} |     \-      |
|  **5**   | M 2/13  |           Random Variables & Probability Distributions            |   3.4, 3.5    |                                        \-                                        | [random-variables-and-probability-distributions](https://posit.cloud/spaces/326046/content/5413426){target="_blank"} |                                        \-                                        |     \-      |
|          | W 2/15  |            Binomial Distribution & Normal Distribution            |   4.1, 4.3    |                                        \-                                        | [binomial-distribution-and-normal-distribution](https://posit.cloud/spaces/326046/content/5428958){target="_blank"}  |                                        \-                                        |     \-      |
|          | F 2/17  |            Case Study: N-games of Rock-Paper-Scissors             |      \-       |                                        \-                                        |              [law-of-large-numbers](https://posit.cloud/spaces/326046/content/5444875){target="_blank"}              |                                        \-                                        |     \-      |
|  **6**   | M 2/20  |                 Foundations of Inference Part 1/2                 |      \-       |                                        \-                                        |             [central-limit-theorem](https://posit.cloud/spaces/326046/content/5456033){target="_blank"}              |                                        \-                                        |     \-      |
|          | W 2/22  |                 Foundations of Inference Part 2/2                 |      \-       |                                        \-                                        |               [hypothesis-testing](https://posit.cloud/spaces/326046/content/5470242){target="_blank"}               |                                        \-                                        |     \-      |
|          | F 2/24  |                            *Cancelled*                            |      \-       |                                        \-                                        |                                                          \-                                                          |                                    Lab 2 Due                                     |     \-      |
|  **7**   | M 2/27  |      Point Estimates and Sampling Variability (Asynchronous)      |      5.1      |                                        \-                                        |    [point-estimates-and-sampling-variability](https://posit.cloud/spaces/326046/content/5497509){target="_blank"}    |                                        \-                                        |     \-      |
|          |  W 3/1  |                  Decision Errors (Asynchronous)                   |      5.3      |                                        \-                                        |                         [decision-errors](https://posit.cloud/spaces/326046/content/5514683){target="_blank"}                         |                                        \-                                        |     \-      |
|          |  F 3/3  |                   Project Period (Asynchronous)                   |      \-       |                                        \-                                        |                                                          \-                                                          |                                        \-                                        | Phase 2 Due |
|  **8**   |  M 3/6  |                            *No Class*                             |      \-       |                                        \-                                        |                                                          \-                                                          |                                        \-                                        |     \-      |
|          |  W 3/8  |                            *No Class*                             |      \-       |                                        \-                                        |                                                          \-                                                          |                                        \-                                        |     \-      |
|          | F 3/10  |                            *No Class*                             |      \-       |                                        \-                                        |                                                          \-                                                          |                                        \-                                        |     \-      |
|  **9**   | M 3/13  |                       Confidence Intervals                        |      5.2      |                                        \-                                        |                                                         TBA                                                          |                                        \-                                        |     \-      |
|          | W 3/15  | Inference for A Single Proportion & Difference of Two Proportions |   6.1, 6.2    |                                        \-                                        |                                                         TBA                                                          |                                        \-                                        |     \-      |
|          | F 3/17  |            Testing for Independence in Two-Way Tables             |   6.3, 6.4    |                                        \-                                        |                                                         TBA                                                          |                                        \-                                        |     \-      |
|  **10**  | M 3/20  |                      Inference for One Mean                       |      7.1      |                                        \-                                        |                                                         TBA                                                          |                                        \-                                        |     \-      |
|          | W 3/22  |                           Paired Means                            |      7.2      |                                        \-                                        |                                                         TBA                                                          |                                        \-                                        |     \-      |
|          | F 3/24  |                      Difference of Two Means                      |      7.3      |                                        \-                                        |                                                         TBA                                                          |                                    Lab 3 Due                                     | Phase 3 Due |
|  **11**  | M 3/27  |                        Power Calculations                         |      7.4      |                                        \-                                        |                                                         TBA                                                          |                                        \-                                        |     \-      |
|          | W 3/29  |                       Comparing Many Means                        |      7.5      |                                        \-                                        |                                                         TBA                                                          |                                        \-                                        |     \-      |
|          | F 3/31  |                          Case Study: TBA                          |      TBA      |                                        \-                                        |                                                         TBA                                                          |                                        \-                                        |     \-      |
|  **12**  |  M 4/3  |                    Linear Regression Part 1/2                     |     8.1.1     |                                        \-                                        |                                                         TBA                                                          |                                        \-                                        |     \-      |
|          |  W 4/5  |                    Linear Regression Part 2/2                     |     8.1.2     |                                        \-                                        |                                                         TBA                                                          |                                        \-                                        |     \-      |
|          |  F 4/7  |                            *No Class*                             |      \-       |                                        \-                                        |                                                          \-                                                          |                                        \-                                        |     \-      |
|  **13**  | M 4/10  |                            *No Class*                             |      \-       |                                        \-                                        |                                                          \-                                                          |                                        \-                                        |     \-      |
|          | W 4/12  |                             Residuals                             | 8.1.3, 8.1.4  |                                        \-                                        |                                                         TBA                                                          |                                        \-                                        |     \-      |
|          | F 4/14  |                     Least Squares Regression                      |      8.2      |                                        \-                                        |                                                         TBA                                                          |                                        \-                                        |     \-      |
|  **14**  | M 4/17  |                         Types of Outliers                         |      8.3      |                                        \-                                        |                                                         TBA                                                          |                                        \-                                        |     \-      |
|          | W 4/19  |                  Inference for Linear Regression                  |      8.4      |                                        \-                                        |                                                         TBA                                                          |                                        \-                                        |     \-      |
|          | F 4/21  |                          Case Study: TBA                          |      TBA      |                                        \-                                        |                                                         TBA                                                          |                                    Lab 4 Due                                     | Phase 4 Due |
|  **15**  | M 4/24  |                        Multiple Regression                        | 9.1, 9.2, 9.3 |                                        \-                                        |                                                         TBA                                                          |                                        \-                                        |     \-      |
|          | W 4/26  |                        Logistic Regression                        |      9.5      |                                        \-                                        |                                                         TBA                                                          |                                        \-                                        |     \-      |
|          | F 4/28  |                          Project Period                           |      \-       |                                        \-                                        |                                                          \-                                                          |                                    Lab 5 Due                                     | Phase 5 Due |
|  **-**   | Tu 5/2  |                  Section A Project Presentations                  |      \-       |                                        \-                                        |                                                          \-                                                          |                                        \-                                        |     \-      |
|          |  W 5/3  |                  Section B Project Presentations                  |      \-       |                                        \-                                        |                                                          \-                                                          |                                        \-                                        |     \-      |

<br>

## **Books & Online Resources Lists**

<br>

### Main Textbook

[OIS] [OpenIntro Statistics (4th edition)](https://www.openintro.org/book/os/){target="_blank"} by David Diez, Mine Cetinkaya-Rundel, and Christopher Barr.
