---
title: '**Confidence Intervals**'
subtitle: "Mini-Assignment - MTH 361 A/B - Spring 2023"
header-includes: |
  \usepackage{fancyhdr}
  \pagestyle{fancy}
  \fancyhead[RO,R]{MTH 361 A/B}
  \fancyfoot[CO,C]{}
  \fancyfoot[R]{\thepage}
  \usepackage{float}
  \usepackage{multirow}
output:
  bookdown::pdf_document2:
    toc: no
    number_section: no
urlcolor: blue
link-citations: yes
bibliography: references.bib
csl: apa.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\

**Instructions:**
 
 * Please provide complete solutions for each problem. If it involves mathematical computations, explanations, or analysis, please provide your reasoning or detailed solutions.
 
 * Note that some problems have multiple solutions or ways to solve it. Make sure that your solutions are clear enough to showcase your work and understanding of the material.
 
 * Creativity and collaborations are encouraged. Use all of the resources you have and what you need to complete the mini-assignment. Each student must take personal responsibility and submit their work individually. Please abide by the University of Portland Academic Honor Principle.
 
 * **Please save your work as one pdf file, don't put your name in any part of the document, and submit it to the Teams Assignments for this course. Your document upload will correspond to your name automatically in Teams.**
 
 * If you have questions or concerns, please feel free to ask the instructor.

\newpage

## I. Introduction to Confidence Intervals

### Materials

The exercises below are derived from the textbook [OpenIntro Statistics (4th edition)](https://www.openintro.org/book/os/){target="_blank"} by David Diez, Mine Cetinkaya-Rundel, and Christopher Barr.

### Exercises

1. **Twitter users and news, Part I.** A poll conducted in 2013 found that 52\% of U.S. adult Twitter users get at least some news on Twitter [@data:pewtwitternews:2013]. The standard error for this estimate was 2.4\%, and a normal distribution may be used to model the sample proportion. Construct a 99\% confidence interval for the fraction of U.S. adult Twitter users who get some news on Twitter, and interpret the confidence interval in context.

2. **Mental health.** The General Social Survey asked the question: ``For how many days during the past 30 days was your mental health, which includes stress, depression, and problems with emotions, not good?" Based on responses from 1,151 US residents, the survey reported a 95\% confidence interval of 3.40 to 4.24 days in 2010.

    a. Interpret this interval in context of the data.
    b. What does ``95\% confident" mean? Explain in the context of the application.
    c. Suppose the researchers think a 99\% confidence level would be more appropriate for this interval. Will this new interval be smaller or wider than the 95\% confidence interval?
    d. If a new survey were to be done with 500 Americans, do you think the standard error of the estimate be larger, smaller, or about the same.

3. (Outstanding Question) **Twitter users and news, Part II.** A poll conducted in 2013 found that 52\% of U.S. adult Twitter users get at least some news on Twitter, and the standard error for this estimate was 2.4\%. Identify each of the following statements as true or false. Provide an explanation to justify each of your answers.

    a. The data provide statistically significant evidence that more than half of U.S. adult Twitter users get some news through Twitter. Use a significance level of $\alpha = 0.01$.
    b. Since the standard error is 2.4\%, we can conclude that 97.6\% of all U.S. adult Twitter users were included in the study.
    c. If we want to reduce the standard error of the estimate, we should collect less data.
    d. If we construct a 90\% confidence interval for the percentage of U.S. adults Twitter users who get some news through Twitter, this confidence interval will be wider than a corresponding 99\% confidence interval.
    
\newpage

## References {#ref}

<div id="refs"></div>