% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={Introduction to R and RStudio},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Introduction to R and RStudio}
\author{}
\date{\vspace{-2.5em}}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{2}
\tableofcontents
}
\hypertarget{the-rstudio-interface}{%
\subsection{The RStudio Interface}\label{the-rstudio-interface}}

The goal of this lab is to introduce you to R and RStudio, which you'll be using throughout the course both to learn the statistical concepts discussed in the course and to analyze real data and come to informed conclusions. To clarify which is which: \texttt{R} is the name of the programming language itself and RStudio is a convenient interface for working with \texttt{R} .

As the labs progress, you are encouraged to explore beyond what the labs dictate; a willingness to experiment will make you a much better programmer! Before we get to that stage, however, you need to build some basic fluency in \texttt{R}. First, we will explore the fundamental building blocks of \texttt{R} and RStudio: the RStudio interface, reading in data, and basic commands for working with data in \texttt{R}.

Go ahead and launch RStudio. You should see a window that looks like the image shown below.

\includegraphics{img/r-interface-2020.png}

The panel on the lower left is where the action happens. This panel is called the \emph{console}. Every time you launch RStudio, it will have the same text at the top of the console telling you the version of R that you're running. Below that information is the \emph{prompt}, indicated by the \texttt{\textgreater{}} symbol. As its name suggests, this prompt is really a request: a request for a command. Initially, interacting with \texttt{R} is all about typing commands and interpreting the output. These commands and their syntax have evolved over decades (literally) and now provide what many users feel is a fairly natural way to access data and organize, describe, and invoke statistical computations.

The panel in the upper right contains your \emph{environment} as well as a history of the commands that you've previously entered.

The panel in the lower right contains tabs for browse the \emph{files} in your project folder, access \emph{help} files for \texttt{R} functions, install and manage \texttt{R} \emph{packages}, and inspecting visualizations. By default, all data visualizations you make will appear directly below the code you used to create them. If you would rather your plots appear in the \emph{plots} tab, you will need to change your global options.

\hypertarget{r-packages}{%
\subsubsection{R Packages}\label{r-packages}}

\texttt{R} is an open-source programming language, meaning that users can contribute packages that make our lives easier, and we can use them for free. For this lab, and many others in the future, we will use the following:

\begin{itemize}
\tightlist
\item
  The \textbf{tidyverse} ``umbrella'' package which houses a suite of many different \texttt{R} packages: for data wrangling and data visualization
\item
  The \textbf{openintro} \texttt{R} package: for data and custom functions with the OpenIntro resources
\end{itemize}

In the lower right hand corner click on the \emph{Packages} tab. Type the name of each of these packages (tidyverse, openintro) into the search box to see if they have been installed. If these packages do not appear when you type in their name, install them by copying and pasting or typing the following two lines of code into the console of your RStudio session. Be sure to press enter/return after each line of code.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{install.packages}\NormalTok{(}\StringTok{"tidyverse"}\NormalTok{)}
\FunctionTok{install.packages}\NormalTok{(}\StringTok{"openintro"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

After pressing enter/return, a stream of text will begin, communicating the process \texttt{R} is going through to install the package from the location you selected when you installed \texttt{R}. If you were not prompted to select a server for downloading packages when you installed \texttt{R}, RStudio may prompt you to select a server from which to download; any of them will work.

You only need to \emph{install} packages once, but you need to \emph{load} them each time you relaunch RStudio. We load packages with the \texttt{library} function. Copy and paste or type the the following two lines in your console to load the tidyverse and openintro packages into your working environment.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tidyverse)}
\FunctionTok{library}\NormalTok{(openintro)}
\end{Highlighting}
\end{Shaded}

We are choosing to use the tidyverse package because it consists of a set of packages necessary for different aspects of working with data, anything from loading data to wrangling data to visualizing data to analyzing data. Additionally, these packages share common philosophies and are designed to work together. You can find more about the packages in the tidyverse at \href{http://tidyverse.org/}{tidyverse.org}.

\hypertarget{creating-a-reproducible-lab-report}{%
\subsubsection{Creating a reproducible lab report}\label{creating-a-reproducible-lab-report}}

We will be using R Markdown to create reproducible lab reports. See the following videos describing why and how:

\href{https://youtu.be/lNWVQ2oxNho}{\textbf{Why use R Markdown for Lab Reports?}}

\href{https://youtu.be/o0h-eVABe9M}{\textbf{Using R Markdown for Lab Reports in RStudio}}

In a nutshell, in RStudio, go to New File -\textgreater{} R Markdown\ldots{} Then, choose ``From Template'' and then choose \texttt{Lab\ Report\ for\ OpenIntro\ Statistics\ Lab\ 1} from the list of templates.

Going forward you should refrain from typing your code directly in the console, as this makes it very difficult to remember and reproduce the output you want to reference. Potentially the most important feature of R Markdown files is that they allow for us to nest our \texttt{R} code within a written report. In an R Markdown file, \texttt{R} code appears in a gray box, which we call ``code chunks.'' The R Markdown file knows that the gray box contains \texttt{R} code because it begins with three tick marks (```), followed by two curly braces that contain a lowercase letter r (\{r\}). You've already seen this above!

Instead of typing our \texttt{R} code into the console, we encourage you to type any code you produce (final correct answer, or anything you're just trying out) in the \texttt{R} code chunk associated with each problem. You can execute the \texttt{R} code you type in these code chunks similar to how you typed code into the console and pressed enter/return. Within the code chunk there are two ways to execute a line of \texttt{R} code: (1) place your cursor on the line on code and press \texttt{Ctrl-Enter} or \texttt{Cmd-Enter} at the same time, or (2) place your cursor on the line and press the ``Run'' button in the upper right hand corner of the R Markdown file. Alternatively, if you wanted to run all of the \texttt{R} code in a given code chunk, you can click on the ``Play'' button in the upper right hand corner of the code chunk (green sideways triangle).

If at any point you need to start over and run all of the code chunks before a specific code chunk, you click on the ``Fastforward'' button in the upper right hand corner of that code chunk (gray upside down triangle with a bar below). This will run every code chunk that occurred \emph{before} that code chunk, but \emph{will not} execute the \texttt{R} code included in that code chunk.

\hypertarget{dr.-arbuthnots-baptism-records}{%
\subsection{Dr.~Arbuthnot's Baptism Records}\label{dr.-arbuthnots-baptism-records}}

To get started, let's take a peek at the data.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{arbuthnot}
\end{Highlighting}
\end{Shaded}

Again, you can run the code above by:

\begin{itemize}
\tightlist
\item
  placing your cursor on the line and pressing \texttt{Ctrl-Enter} or \texttt{Cmd-Enter}
\item
  placing your cursor on the line and pressing the ``Run'' button in the upper right hand corner of the R Markdown file, or
\item
  by clicking on the green arrow at the top right hand corner of the code chunk
\end{itemize}

The single line of code included in this code chunk instructs \texttt{R} to load some data: the Arbuthnot baptism counts for boys and girls. You should see that the \emph{Environment} tab in the upper right hand corner of the RStudio window now lists a data set called \texttt{arbuthnot} that has 82 observations on 3 variables. As you interact with \texttt{R}, you will create objects for a variety of purposes. Sometimes you load the objects into your workspace by loading a package, as we have done here, but sometimes you create objects yourself as a byproduct of a computation process, for an analysis you have performed, or for a visualization you have created.

The Arbuthnot data set refers to the work of Dr.~John Arbuthnot, an 18th century physician, writer, and mathematician. He was interested in the ratio of newborn boys to newborn girls, so he gathered the baptism records for children born in London for every year from 1629 to 1710. Once again, we can view the data by running the code below or by typing the name of the dataset into the console. Be careful the spelling and capitalization you use! \texttt{R} is case sensitive, so if you accidentally type \texttt{Arbuthnot} \texttt{R} will tell you that object cannot be found.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{arbuthnot}
\end{Highlighting}
\end{Shaded}

This command does display the data for us, however, printing the whole dataset in the console is not that useful. One advantage of RStudio is that it comes with a built-in data viewer. The \emph{Environment} tab (in the upper right pane) lists the objects in your environment. Clicking on the name \texttt{arbuthnot} will open up a \emph{Data Viewer} tab next to your R Markdown file, which provides an alternative display of the data set. This display should feel similar to viewing data in Excel, where you are able to scroll through the dataset to inspect it. However, unlike Excel, you \textbf{will not} be able to edit the data in this tab. Once you are done viewing the data, You can close this tab by clicking on the \texttt{x} in the upper left hand corner.

When inspecting the data, you should see four columns of numbers and 82 rows. Each row represents a different year that Arbuthnot collected data. The first entry in each row is the row number (an index we can use to access the data from individual years if we want), the second is the year, and the third and fourth are the numbers of boys and girls baptized that year, respectively. Use the scrollbar on the right side of the console window to examine the complete data set.

Note that the row numbers in the first column are not part of Arbuthnot's data. \texttt{R} adds these row numbers as part of its printout to help you make visual comparisons. You can think of them as the index that you see on the left side of a spreadsheet. In fact, the comparison of the data to a spreadsheet will generally be helpful. \texttt{R} has stored Arbuthnot's data in an object similar to a spreadsheet or a table, which \texttt{R} calls a \emph{data frame}.

You can see the dimensions of this data frame as well as the names of the variables and the first few observations by inserting the name of the dataset into the \texttt{glimpse()} function, as seen below:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{glimpse}\NormalTok{(arbuthnot)}
\end{Highlighting}
\end{Shaded}

Although we previously said that it is best practice to type all of your \texttt{R} code into the code chunk, it is better practice to type this command into your console. Generally, you should type all of the code that is necessary for your solution into the code chunk. Because this command is used to explore the data, it is not necessary for your solution code and \textbf{should not} be included in your solution file.

This command should output the following:

\begin{verbatim}
## Rows: 82
## Columns: 3
## $ year  <int> 1629, 1630, 1631, 1632, 1633, 1634, 1635, 1636, 1637, 1638, 1639~
## $ boys  <int> 5218, 4858, 4422, 4994, 5158, 5035, 5106, 4917, 4703, 5359, 5366~
## $ girls <int> 4683, 4457, 4102, 4590, 4839, 4820, 4928, 4605, 4457, 4952, 4784~
\end{verbatim}

We can see that there are 82 observations and 3 variables in this dataset. The variable names are \texttt{year}, \texttt{boys}, and \texttt{girls}. At this point, you might notice that many of the commands in \texttt{R} look a lot like functions from math class; that is, invoking \texttt{R} commands means supplying a function with some number of inputs (what are called arguments) which the function uses to produce an output. The \texttt{glimpse()} command, for example, took a single argument, the name of a data frame and produced a display of the dataset as an output.

\hypertarget{some-exploration}{%
\subsection{Some Exploration}\label{some-exploration}}

Let's start to examine the data a little more closely. We can access the data in a single column of a data frame by extracting the column with a \texttt{\$}. For example, the code below extracts the \texttt{boys} column from the \texttt{arbuthnot} data frame.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{arbuthnot}\SpecialCharTok{$}\NormalTok{boys}
\end{Highlighting}
\end{Shaded}

This command will only show the number of boys baptized each year. \texttt{R} interprets the \texttt{\$} as saying ``go to the data frame that comes before me, and find the variable that comes after me.''

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  What command would you use to extract just the counts of girls baptized? Try it out in the console!
\end{enumerate}

Notice that the way \texttt{R} has printed these data is different. When we looked at the complete data frame, we saw 82 rows, one on each line of the display. These data have been extracted from the data frame, so they are no longer structured in a table with other variables. Instead, these data are displayed one right after another. Objects that print out in this way are called \emph{vectors}; similar to the vectors you have seen in mathematics courses, vectors represent a list of numbers. \texttt{R} has added numbers displayed in {[}brackets{]} along the left side of the printout to indicate each entry's location within the vector. For example, 5218 follows \texttt{{[}1{]}}, indicating that \texttt{5218} is the first entry in the vector. If \texttt{{[}43{]}} was displayed at the beginning of a line, that indicate that the first number displayed on that line would correspond to the 43rd entry in that vector.

\hypertarget{data-visualization}{%
\subsubsection{Data visualization}\label{data-visualization}}

\texttt{R} has some powerful functions for making graphics. We can create a simple plot of the number of girls baptized per year with the following code:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data =}\NormalTok{ arbuthnot, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ year, }\AttributeTok{y =}\NormalTok{ girls)) }\SpecialCharTok{+} 
  \FunctionTok{geom\_point}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{intro_to_r_files/figure-latex/plot-girls-vs-year-1.pdf}

In this code, we use the \texttt{ggplot()} function to build a plot. If you run this code chunk, a plot will appear below the code chunk. The R Markdown document displays the plot below the code that was used to generate it, to give you an idea of what the plot would look like in a final report.

The command above also looks like a mathematical function. This time, however, the function requires multiple inputs (arguments), which are separated by commas.

With \texttt{ggplot()}:

\begin{itemize}
\tightlist
\item
  The first argument is always the name of the dataset you wish to use for plotting.
\item
  Next, you provide the variables from the dataset to be assigned to different \texttt{aes}thetic elements of the plot, such as the x and the y axes.
\end{itemize}

These commands will build a blank plot, with the variables you assigned to the x and y axes. Next, you need to tell \texttt{ggplot()} what type of visualization you would like to add to the blank template. You add another layer to the \texttt{ggplot()} by:

\begin{itemize}
\tightlist
\item
  adding a \texttt{+} at the end of the line, to indicate that you are adding a layer
\item
  then specify the \texttt{geom}etric object to be used to create the plot.
\end{itemize}

Since we want to scatterplot, we use \texttt{geom\_point()}. This tells \texttt{ggplot()} that each data point should be represented by one point on the plot. If you wanted to visualize the above plot using a line graph instead of a scatterplot, you would replace \texttt{geom\_point()} with \texttt{geom\_line()}. This tells \texttt{ggplot()} to draw a line from each observation with the next observation (sequentially).

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data =}\NormalTok{ arbuthnot, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ year, }\AttributeTok{y =}\NormalTok{ girls)) }\SpecialCharTok{+}
  \FunctionTok{geom\_line}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{intro_to_r_files/figure-latex/plot-girls-vs-year-line-1.pdf}

Use the plot to address the following question:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Is there an apparent trend in the number of girls baptized over the years? How would you describe it? (To ensure that your lab report is comprehensive, be sure to include the code needed to make the plot as well as your written interpretation.)
\end{enumerate}

You might wonder how you are supposed to know the syntax for the \texttt{ggplot()} function. Thankfully, \texttt{R} documents all of its functions extensively. To learn what a function does and how to use it (e.g.~the function's arguments), just type in a question mark followed by the name of the function that you're interested in into the console. Type the following in your console:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{?ggplot}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## starting httpd help server ... done
\end{verbatim}

Notice that the help file comes to the forefront, replacing the plot in the lower right panel. You can toggle between the tabs by clicking on their names.

\hypertarget{r-as-a-big-calculator}{%
\subsubsection{R as a big calculator}\label{r-as-a-big-calculator}}

Now, suppose we want to plot the total number of baptisms. To compute this, we could use the fact that we can use \texttt{R} as a big calculator. To do this, we can type in mathematical expressions such as the below calculation into the console.

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{5218} \SpecialCharTok{+} \DecValTok{4683}
\end{Highlighting}
\end{Shaded}

This calculation would provide us with the total number of baptisms in 1629. We could then repeat this calculation once for each year. This would probably take us a while, but luckily there is a faster way! If we add the vector for baptisms for boys to that of girls, \texttt{R} can compute each of these sums simultaneously.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{arbuthnot}\SpecialCharTok{$}\NormalTok{boys }\SpecialCharTok{+}\NormalTok{ arbuthnot}\SpecialCharTok{$}\NormalTok{girls}
\end{Highlighting}
\end{Shaded}

What you will see is a list of 82 numbers. These numbers appear as a list, because we are working with vectors rather than a data frame. Each number represents the sum of how many boys and girls were baptized that year. You can take a look at the first few rows of the \texttt{boys} and \texttt{girls} columns to see if the calculation is right.

\hypertarget{adding-a-new-variable-to-the-data-frame}{%
\subsubsection{Adding a new variable to the data frame}\label{adding-a-new-variable-to-the-data-frame}}

We are interested in using this new vector of the total number of baptisms to generate some plots, so we'll want to save it as a permanent column in our data frame. We can do this using the following code:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{arbuthnot }\OtherTok{\textless{}{-}}\NormalTok{ arbuthnot }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{total =}\NormalTok{ boys }\SpecialCharTok{+}\NormalTok{ girls)}
\end{Highlighting}
\end{Shaded}

This code has a lot of new pieces to it, so let's break it down. In the first line we are doing two things, (1) adding a new \texttt{total} column to this updated data frame, and (2) overwriting the existing \texttt{arbutnot} data frame with an updated data frame that includes the new \texttt{total} column. We are able to chain these two processes together using the \textbf{piping} (\texttt{\%\textgreater{}\%}) operator. The piping operator takes the output of the previous expression and ``pipes it'' into the first argument of the next expression.

To continue our analogy with mathematical functions, \texttt{x\ \%\textgreater{}\%\ f(y)} is equivalent to \texttt{f(x,\ y)}. Connecting \texttt{arbuthnot} and \texttt{mutate(total\ =\ boys\ +\ girls)} with the pipe operator is the same as typing \texttt{mutate(arbuthnot,\ total\ =\ boys\ +\ girls)}, where \texttt{arbuthnot} becomes the first argument included in the \texttt{mutate()} function.

\leavevmode\vadjust pre{\hypertarget{boxedtext}{}}%
\textbf{A note on piping:} Note that we can read these two lines of code as the following:

\emph{``Take the \texttt{arbuthnot} dataset and \textbf{pipe} it into the \texttt{mutate} function. Mutate the \texttt{arbuthnot} data set by creating a new variable called \texttt{total} that is the sum of the variables called \texttt{boys} and \texttt{girls}. Then assign the resulting dataset to the object called \texttt{arbuthnot}, i.e.~overwrite the old \texttt{arbuthnot} dataset with the new one containing the new variable.''}

This is equivalent to going through each row and adding up the \texttt{boys} and \texttt{girls} counts for that year and recording that value in a new column called \texttt{total}.

\textbf{Where is the new variable?} When you make changes to variables in your dataset, click on the name of the dataset again to update it in the data viewer.

You'll see that there is now a new column called \texttt{total} that has been tacked onto the data frame. The special symbol \texttt{\textless{}-} performs an \emph{assignment}, taking the output of the piping operations and saving it into an object in your environment. In this case, you already have an object called \texttt{arbuthnot} in your environment, so this command updates that data set with the new mutated column.

You can make a line plot of the total number of baptisms per year with the following code:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data =}\NormalTok{ arbuthnot, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ year, }\AttributeTok{y =}\NormalTok{ total)) }\SpecialCharTok{+} 
  \FunctionTok{geom\_line}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{intro_to_r_files/figure-latex/plot-total-vs-year-1.pdf}

In an similar fashion, once you know the total number of baptisms for boys and girls in 1629, you can compute the ratio of the number of boys to the number of girls baptized with the following code:

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{5218} \SpecialCharTok{/} \DecValTok{4683}
\end{Highlighting}
\end{Shaded}

Alternatively, you could calculate this ratio for every year by acting on the complete \texttt{boys} and \texttt{girls} columns, and then save those calculations into a new variable named \texttt{boy\_to\_girl\_ratio}:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{arbuthnot }\OtherTok{\textless{}{-}}\NormalTok{ arbuthnot }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{boy\_to\_girl\_ratio =}\NormalTok{ boys }\SpecialCharTok{/}\NormalTok{ girls)}
\end{Highlighting}
\end{Shaded}

You can also compute the proportion of newborns that are boys in 1629 with the following code:

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{5218} \SpecialCharTok{/}\NormalTok{ (}\DecValTok{5218} \SpecialCharTok{+} \DecValTok{4683}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Or you can compute this for all years simultaneously and add it as a new variable named \texttt{boy\_ratio} to the dataset:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{arbuthnot }\OtherTok{\textless{}{-}}\NormalTok{ arbuthnot }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{boy\_ratio =}\NormalTok{ boys }\SpecialCharTok{/}\NormalTok{ total)}
\end{Highlighting}
\end{Shaded}

Notice that rather than dividing by \texttt{boys\ +\ girls} we are using the \texttt{total} variable we created earlier in our calculations!

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  Now, generate a plot of the proportion of boys born over time. What do you see?
\end{enumerate}

\textbf{Tip:} If you use the up and down arrow keys in the console, you can scroll through your previous commands, your so-called command history. You can also access your command history by clicking on the history tab in the upper right panel. This can save you a lot of typing in the future.

Finally, in addition to simple mathematical operators like subtraction and division, you can ask R to make comparisons like greater than, \texttt{\textgreater{}}, less than, \texttt{\textless{}}, and equality, \texttt{==}. For example, we can create a new variable called \texttt{more\_boys} that tells us whether the number of births of boys outnumbered that of girls in each year with the following code:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{arbuthnot }\OtherTok{\textless{}{-}}\NormalTok{ arbuthnot }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{more\_boys =}\NormalTok{ boys }\SpecialCharTok{\textgreater{}}\NormalTok{ girls)}
\end{Highlighting}
\end{Shaded}

This command adds a new variable to the \texttt{arbuthnot} data frame containing the values of either \texttt{TRUE} if that year had more boys than girls, or \texttt{FALSE} if that year did not (the answer may surprise you). This variable contains a different kind of data than we have encountered so far. All other columns in the \texttt{arbuthnot} data frame have values that are numerical (the year, the number of boys and girls). Here, we've asked R to create \emph{logical} data, data where the values are either \texttt{TRUE} or \texttt{FALSE}. In general, data analysis will involve many different kinds of data types, and one reason for using \texttt{R} is that it is able to represent and compute with many of them.

\hypertarget{more-practice}{%
\subsection{More Practice}\label{more-practice}}

In the previous few pages, you recreated some of the displays and preliminary analysis of Arbuthnot's baptism data. Your assignment involves repeating these steps, but for present day birth records in the United States. The data are stored in a data frame called \texttt{present}.

To find the minimum and maximum values of columns, you can use the functions \texttt{min()} and \texttt{max()} within a \texttt{summarize()} call, which you will learn more about in the following lab.

Here's an example of how to find the minimum and maximum amount of boy births in a year:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{arbuthnot }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarize}\NormalTok{(}\AttributeTok{min =} \FunctionTok{min}\NormalTok{(boys),}
            \AttributeTok{max =} \FunctionTok{max}\NormalTok{(boys)}
\NormalTok{            )}
\end{Highlighting}
\end{Shaded}

Answer the following questions with the \texttt{present} data frame:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  What years are included in this data set? What are the dimensions of the data frame? What are the variable (column) names?
\item
  How do these counts compare to Arbuthnot's? Are they of a similar magnitude?
\item
  Make a plot that displays the proportion of boys born over time. What do you see? Does Arbuthnot's observation about boys being born in greater proportion than girls hold up in the U.S.? Include the plot in your response. \emph{Hint:} You should be able to reuse your code from Exercise 3 above, just replace the name of the data frame.
\item
  In what year did we see the most total number of births in the U.S.? \emph{Hint:} First calculate the totals and save it as a new variable. Then, sort your dataset in descending order based on the \texttt{total} column. You can do this interactively in the data viewer by clicking on the arrows next to the variable names. To include the sorted result in your report you will need to use two new functions. First we use \texttt{arrange()} to sorting the variable. Then we can arrange the data in a descending order with another function, \texttt{desc()}, for descending order. The sample code is provided below.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{present }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{arrange}\NormalTok{(}\FunctionTok{desc}\NormalTok{(total))}
\end{Highlighting}
\end{Shaded}

These data come from reports by the Centers for Disease Control. You can learn more about them by bringing up the help file using the command \texttt{?present}.

\hypertarget{resources-for-learning-r-and-working-in-rstudio}{%
\subsection{Resources for learning R and working in RStudio}\label{resources-for-learning-r-and-working-in-rstudio}}

That was a short introduction to R and RStudio, but we will provide you with more functions and a more complete sense of the language as the course progresses.

In this course we will be using the suite of R packages from the \textbf{tidyverse}. The book \href{https://r4ds.had.co.nz/}{R For Data Science} by Grolemund and Wickham is a fantastic resource for data analysis in R with the tidyverse. If you are Goggling for R code, make sure to also include these package names in your search query. For example, instead of Goggling ``scatterplot in R'', Goggle ``scatterplot in R with the tidyverse''.

These may come in handy throughout the semester:

\begin{itemize}
\tightlist
\item
  \href{https://github.com/rstudio/cheatsheets/raw/main/rmarkdown-2.0.pdf}{RMarkdown cheatsheet}
\item
  \href{https://github.com/rstudio/cheatsheets/raw/main/data-transformation.pdf}{Data transformation cheatsheet}
\item
  \href{https://github.com/rstudio/cheatsheets/raw/main/data-visualization-2.1.pdf}{Data visualization cheatsheet}
\end{itemize}

Note that some of the code on these cheatsheets may be too advanced for this course. However the majority of it will become useful throughout the semester.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\includegraphics{https://i.creativecommons.org/l/by-sa/4.0/88x31.png}This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.

\end{document}
